"""job sightings for repost detection

Revision ID: 44876f72c27a
Revises: fe3e9ced84ce
Create Date: 2026-09-25 10:25:39.758623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44876f72c27a'
down_revision: Union[str, Sequence[str], None] = 'fe3e9ced84ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sightings',
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('sample_title', sa.String(length=300), nullable=True),
    sa.Column('sample_company', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    op.create_index('ix_sightings_first_seen', 'job_sightings', ['first_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sightings_first_seen', table_name='job_sightings')
    op.drop_table('job_sightings')
    # ### end Alembic commands ###
