"""applicant portal: profiles, positions, applications

Revision ID: 5be63adc0bc5
Revises: 7704289b170c
Create Date: 2026-09-24 21:15:33.008434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be63adc0bc5'
down_revision: Union[str, Sequence[str], None] = '7704289b170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('soc_code', sa.String(length=10), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='positionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_title'), 'positions', ['title'], unique=False)
    op.create_table('applicant_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_role', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_profiles_user_id'), 'applicant_profiles', ['user_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('applicant_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'in_review', 'interview', 'offer', 'rejected', 'withdrawn', name='applicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_applicant_id'), 'applications', ['applicant_id'], unique=False)
    op.create_index('ix_applications_applicant_status', 'applications', ['applicant_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_position_id'), 'applications', ['position_id'], unique=False)
    op.create_index('ix_applications_position_status', 'applications', ['position_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index('ix_applications_position_status', table_name='applications')
    op.drop_index(op.f('ix_applications_position_id'), table_name='applications')
    op.drop_index('ix_applications_applicant_status', table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_applicant_profiles_user_id'), table_name='applicant_profiles')
    op.drop_table('applicant_profiles')
    op.drop_index(op.f('ix_positions_title'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
