"""remove Position: candidate-side only

Revision ID: 85c8a66ab8f3
Revises: ff770e76dd81
Create Date: 2026-09-25 11:23:02.518152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85c8a66ab8f3'
down_revision: Union[str, Sequence[str], None] = 'ff770e76dd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Order matters: the FK on applications.position_id depends on the
    # positions table, so the column (and its constraint) must go first.
    # Alembic autogenerated these the other way round, which Postgres
    # refuses with DependentObjectsStillExist.
    op.drop_index("ix_applications_position_status", table_name="applications")
    op.drop_index("ix_applications_position_id", table_name="applications")
    op.drop_constraint("applications_position_id_fkey", "applications", type_="foreignkey")
    op.drop_column("applications", "position_id")

    op.drop_index("ix_positions_title", table_name="positions")
    op.drop_table("positions")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('position_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('applications_position_id_fkey'), 'applications', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_applications_position_status'), 'applications', ['position_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_position_id'), 'applications', ['position_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('soc_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('positions_pkey'))
    )
    op.create_index(op.f('ix_positions_title'), 'positions', ['title'], unique=False)
    # ### end Alembic commands ###
