"""application events can be undos

Revision ID: a87f0fdf6df7
Revises: 85c8a66ab8f3
Create Date: 2026-09-25 23:56:27.731927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87f0fdf6df7'
down_revision: Union[str, Sequence[str], None] = '85c8a66ab8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_events', sa.Column('is_undo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_events', 'is_undo')
    # ### end Alembic commands ###
