"""applications track external jobs

Revision ID: ff770e76dd81
Revises: 44876f72c27a
Create Date: 2026-09-25 10:31:24.703413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff770e76dd81'
down_revision: Union[str, Sequence[str], None] = '44876f72c27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('source', sa.String(length=32), nullable=False))
    op.add_column('applications', sa.Column('external_id', sa.String(length=120), nullable=True))
    op.add_column('applications', sa.Column('fingerprint', sa.String(length=32), nullable=True))
    op.add_column('applications', sa.Column('job_title', sa.String(length=300), nullable=True))
    op.add_column('applications', sa.Column('company', sa.String(length=200), nullable=True))
    op.add_column('applications', sa.Column('job_location', sa.String(length=200), nullable=True))
    op.add_column('applications', sa.Column('job_url', sa.String(length=1000), nullable=True))
    op.add_column('applications', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.alter_column('applications', 'position_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index('ix_applications_applicant_fingerprint', 'applications', ['applicant_id', 'fingerprint'], unique=False)
    op.create_index(op.f('ix_applications_fingerprint'), 'applications', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_fingerprint'), table_name='applications')
    op.drop_index('ix_applications_applicant_fingerprint', table_name='applications')
    op.alter_column('applications', 'position_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('applications', 'salary_max')
    op.drop_column('applications', 'salary_min')
    op.drop_column('applications', 'job_url')
    op.drop_column('applications', 'job_location')
    op.drop_column('applications', 'company')
    op.drop_column('applications', 'job_title')
    op.drop_column('applications', 'fingerprint')
    op.drop_column('applications', 'external_id')
    op.drop_column('applications', 'source')
    # ### end Alembic commands ###
